version: '3.7'

services:
  app:
    image: back
    container_name: 'cloud-service'
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_base_test
    ports:
    - "3309:3309"
    volumes:
    - ./data/db:/var/lib/mysql